### ISSUE TITLE
the_content missing

### ISSUE THREAD

**Issue by bodhi1970** [elementor/hello-theme#101]
I am working currently on a page with paidmembership plugin and on some pages where I only should include a shortcode I get the error message that "the_content" is missing.
I read on the Elementor tutorials that this can be included in the theme but most theme have that. Themes Hello-Theme does not have that.
Can you include it?
![Screen Shot 2019-11-13 at 15 07 00](https://user-images.githubusercontent.com/5292941/68771870-20af3300-0629-11ea-8abe-2af2fac90cf6.png)

**Comment by Bugreal** [comment]
The Hello theme does use the_content function:
https://github.com/elementor/hello-theme/search?q=the_content&unscoped_q=the_content

The issue is likely due to a conflict with the membership plugin you are using (or with another third-party product).
The official documentation explains that most of the themes include this function: _"Important! You do not have to add this code if you are not the developer of a theme. The majority of WordPress themes include this function in the regular pages and posts."_
(https://docs.elementor.com/article/56-content-area-not-found) The majority of the themes means something like 99% of the themes.

For assistance with issues linked to Elementor, you can receive support via the repository of WP or via your Elementor account.

**Comment by nuritsha** [comment]
Hi @bodhi1970,

As explained by @Bugreal , the Elementor Hello theme includes `the_content()` as part of its single.php.
The issue seems to result from the membership plugin you are using.
For further assistance, please contact the Elementor support team.

Thanks

**Comment by DianaDevelopful** [comment]
Hi
I'm commenting on this issue because I have the same problem when I try to edit a header or footer while version 3.4.7 is active. The problem vanishes immediately when I switch to the Astra Theme, and it also resolves itself after some time when I use an older version of the Hello Theme. Elementor Cache is disabled and there is no other cache plugin installed on the page.

I can see the function in the single.php file when I open it, but it somehow doesn't seem to load correctly. At least not immediately.
