### ISSUE TITLE
Could you guys add support for Admin Menu Walker 5.4

### ISSUE THREAD

**Issue by ShaneLynam** [elementor/hello-theme#117]
A plugin I use to control nav Item visibility used to replace this code itself but now the wordpress core handles it so the dev of the plugin took it out. She's saying in this thread it's the theme developer who needs to support it now. 

https://wordpress.org/support/topic/menu-items-invisible-2

https://wordpress.org/plugins/nav-menu-roles/#instructions%20for%20patching%20your%20plugin%2Ftheme

In the links above the plugin dev explains the fix which I would rather not to manually as I'm not a theme developer.

Thanks!

**Comment by jhanten** [comment]
Since you are probably using Elementor could you duplicate the behavior you want with this plugin?

https://wordpress.org/plugins/dynamic-visibility-for-elementor/

Jonathon


Jonathon Hanten
Webmaster
Office of Communications
2401 Lake Park Dr. SE • Smyrna, GA • 30080
o: 404.920.7343 • f: 404.920.7341
jhanten@archatl.com •  pastoralplan.archatl.com<https://archatl.com/pastoral-plan/>

[http://archatl.com/email/aoa-email-logo.png]

Confidentiality Notice: This message contains confidential information and is intended only for the individual named. This communication may contain information that is proprietary, privileged or confidential. If you are not the named addressee, you are not authorized to read, print, retain, copy or disseminate this message or any part of it. If you have received this message in error, please notify the sender immediately by e-mail and delete all copies of the message.

**Comment by jazir5** [comment]
@ShaneLynam 

Dynamic content for elementor's visibility module will work for you: https://www.dynamic.ooo/

Use the role based settings to hide it for the woocommerce customer role

**Comment by rami-elementor** [comment]
Closing. We are not planning to add support for Admin Menu Walker 5.4
