### ISSUE TITLE
🐞 Hello theme adds top margin to heading tags [please remove]

### ISSUE THREAD

**Issue by perks98** [elementor/hello-theme#230]
I have tried to start using the Hello theme more for certain projects. Something that I have noticed was an alignment issue on an icon box widget I was using [example below] but this became impossible as from checking the CSS it seems all headings had an added top margin, so I have to now use custom CSS to remove. But certain widgets like the heading widget aren't affected while the text editor widget is. This just needs to be removed globally as it is meant to be a stripped-back theme, if you have added this option please allow somewhere in the theme customiser settings to remove this option.

![Screenshot 2022-10-11 093305](https://user-images.githubusercontent.com/55829113/195040434-3b163446-da7d-44d7-8e29-96de1e14b013.png)

https://user-images.githubusercontent.com/55829113/195040977-0218f530-dbad-4d85-9bb3-c528efc537e6.mp4

**Comment by arielk** [comment]
Hi @perks98,

Due to compatibility issues between default browser settings we had to set general reset settings for the theme (you can see more here: https://github.com/elementor/hello-theme/blob/master/assets/scss/reset/_reset.scss#L43).

Unfortunately we can't just remove it, so I can recommend you for now to use custom CSS code on your customizer that will remove it.

```
h1, h2, h3, h4, h5, h6 {
	margin-top: 0;
}
```

**Comment by perks98** [comment]
@arielk I will create a new issue under the Elementor issues thread then as the icon box widget shouldn't have a top margin. Just for reference, I think this still needs to be fixed on your side as I have used many themes in the past and it is only the hello theme that I have this issue with which is disappointing.
