### ISSUE TITLE
attachment.php template

### ISSUE THREAD

**Issue by RobertShippey** [elementor/hello-theme#80]
Hi there, 

We use the Hello theme and we're trying to create a template for the attachment pages. 
It seems like it should be possible as the attachment.php template is listed here https://developers.elementor.com/theme-locations-api/ but I can't seem to find where to create one in Elementor itself. Can you help please?

**Comment by nuritsha** [comment]
Hi @RobertShippey,

If I understand correctly what you are aiming for, then the process is actually simpler and doesn't require changing the Hello theme or using the theme locations API.
Use the Elementor Pro Theme Builder to create a new single template and use the conditions in order to assign it to Media.

**Comment by RobertShippey** [comment]
@nuritsha I thought it should be that simple, however the Media option isn't there? Any hints? 
![Screen Shot 2019-07-09 at 15 47 13](https://user-images.githubusercontent.com/787949/60898316-e5f35380-a260-11e9-9168-9ea4a73eb716.png)

**Comment by nuritsha** [comment]
Just go ahead and pick `post` (it will not impact the template itself just filters the list of pre-designed templates that are suggested to you).
After you design the template, use the Display Conditions to assign it to the Media.
![image](https://user-images.githubusercontent.com/43785095/60898857-2c04e300-a272-11e9-9dae-a4031440c666.png)

**Comment by RobertShippey** [comment]
@nuritsha Ooooooh! Thank you. Now I can't seem to find how to get the actual media image in the template? "Post Content" shows it in the editor but not on the front-end. Featured image doesn't work either. 
Thanks for your help so far on this.

**Comment by nuritsha** [comment]
Post content should do the trick.
But you will not see it in the editor.
You need to navigate to the attachment page (thru the media item page, there is a link)

**Comment by RobertShippey** [comment]
I've got the reverse happening. I see the image in the editor, but not on the actual attachment page. e.g https://www.acornworks.co.uk/mezzanine-floors/mezzanine-floor-01/
The text "Acorn Works Ltd supplied and installed this..." is pulled in via "Post Content" as seen in the screenshot above.

**Comment by nuritsha** [comment]
I see. I need access to the site admin in order to debug. Please contact support @elementor.com with the login credentials add the issue number and request them to escalate to me. In any case, it is not related the the theme but to the E-Pro plugin.

**Comment by nuritsha** [comment]
Hi @RobertShippey,

I checked your site, it looks like a theme issue, once I switched to the Elementor Hello theme, the image appears. 
Note that you do not need the Featured Image widget, since for media posts, the post content is the image.
I switched the theme back but left the Elementor Hello for you to check.
Also - I created a new template "new-attachment" without the Featured Image widget and set the conditions to use it instead of your original template.
