### ISSUE TITLE
Please let me set typography for post comments.

### ISSUE THREAD

**Issue by richpav** [elementor/hello-theme#93]
The Post Comment widget can only inherit typography from the theme. Please add the ability to set the default typography in Wordpress theme customization. I had to switch to Astra, although I didn't want to.

In the comments widget, there's a "Skin = Theme Comments" pulldown menu with no alternative selections. I'm not an expert and neither the Elementor docs nor Googling helped me understand how to use that feature.

**Comment by nuritsha** [comment]
Hi @richpav,

You are correct, but it is by design - the Hello theme is a minimal theme, doing the minimal required to set the environment for Elementor.

There are two options to solve your issue:
1) Create a child theme and then either set the style you want using css in style.css or changing the entire comments template by overriding comments.php.
2) Extend the Comments widget and add a new skin.

Also, you can submit it to the [Elementor repo](https://github.com/elementor/elementor) as a change request. 

Thanks!
